#!/usr/bin/env bash
# If not running interactively, don't do anything
# [ $TERM = "dumb" ] && return
case $- in
    *i*) ;;
    *) return;;
esac

export TERM="xterm-256color"
# required by emacs shell (can also be set -o vi)
set -o emacs
# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTCONTROL=ignoreboth:erasedups HISTSIZE=100000 HISTFILESIZE=200000
PROMPT_COMMAND='history -a'

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

complete -cf sudo

[ -f ~/.bash_aliases ] && . ~/.bash_aliases
[ -f /etc/bash_completion ] && ! shopt -oq posix && . /etc/bash_completion
[ -f /usr/share/fzf/completion.bash ] && . /usr/share/fzf/completion.bash
[ -f /usr/share/fzf/key-bindings.bash ] && . /usr/share/fzf/key-bindings.bash

C1="\[$(tput setaf 1)\]"
C2="\[$(tput setaf 2)\]"

RS="\[$(tput sgr0)\]" # <- not compatible with emacs shell
# infocmp -l ansi | rg sgr0 -> change \E to \033
[ -z $TERM_FROM_EMACS ] && [ ! -z $EMACS_SHELL ] && RS="\033[0;10m"

# PS1 config
export PS1=" ${C1}\w${RS}\n ${C2}${RS} "
# export PS1=" \w\n  "

export EDITOR="emacsclient"
export FZF_DEFAULT_OPTS="--color 16"
# Required for MATLAB to work while using bspwm
export _JAVA_AWT_WM_NONREPARENTING=1
# Java
export JAVA_HOME="/usr/lib/jvm/default"

eval "$(direnv hook bash)"