#!/bin/sh

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors false
bspc config pointer_modifier
bspc config border_width         0 # 2
bspc config window_gap           5
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a "Emacs" state=tiled follow=on
bspc rule -a "GNU Octave" state=floating
