#!/usr/bin/env sh
scriptdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

"$scriptdir/monitor" "-n"

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors false
bspc config pointer_modifier
bspc config border_width         2 # 2
bspc config window_gap           5
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a "Emacs" state=tiled follow=on
bspc rule -a "GNU Octave" state=floating
# Scratchpad (For st change to "scratchpad:*:*")
bspc rule -a "*:scratchpad" sticky=on state=floating hidden=off rectangle=1912x440+4+4