#!/usr/bin/env sh
scriptdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

sleep 0.1s

"$scriptdir/monitor" "-n"

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors false
bspc config pointer_modifier
bspc config border_width         2 # 2
bspc config focused_border_color "#fdaa3a"
bspc config window_gap           5
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a "Emacs" state=tiled follow=on # desktop=I
bspc rule -a "GNU Octave" state=floating
# Scratchpad (For st change to "scratchpad:*:*")
dimensions="`xrandr | rg -o -e 'connected.* (\d+x\d+)' -r '$1'`"
readarray -d x -t wh <<< "$dimensions"
w=$((${wh[0]} - 8))
[ ${wh[1]} -gt 1080 ] && h=840 || h=520
bspc rule -a "*:scratchpad" sticky=on state=floating hidden=off rectangle=$w"x"$h+4+4

bspc config external_rules_command "$scriptdir/external_rules"
# Set the default X-shaped cursor to normal left click cursor
xsetroot -cursor_name left_ptr