#!/usr/bin/env bash
# Some steps have to be done manually after a fresh installation
# This script is meant to guide me through all of these steps so I do not forget anything

# Add sync folder to syncthing (mayb automate this via nix)
[ -d $HOME/Sync ] && rm -r $HOME/Sync
qutebrowser http://10.10.10.3:9004/
qutebrowser http://127.0.0.1:8384/

# Generate Yubikey first challenge filse in ~/.yubico/challenge-selial
nix-shell -p yubico-pam --command 'ykpamcfg -2'

# Add gpg key
gpg --import ~/sync/app_data/pubkeys/phga.pub
gpg --edit-key phga # trust 5

# RUN link.sh